run:
  timeout: 3m
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt

linters-settings:
  gofmt:
    simplify: true

